# Generated by Django 3.2 on 2023-10-11 10:43

from django.db import migrations
import json


def load_data(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Tag = apps.get_model('recipes', 'Tag')
    with open('data/ingredients.json', 'r', encoding='utf-8') as file:
        data = json.load(file)
        for item in data:
            Ingredient.objects.create(
                name=item['name'], measurement_unit=item['measurement_unit']
            )
    with open('data/tags.json', 'r', encoding='utf-8') as file:
        data = json.load(file)
        for item in data:
            Tag.objects.create(
                name=item['name'], color=item['color'], slug=item['slug']
            )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
